[package]
name = "neetcode150"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
path="01_arrays_and_hashing/lib.rs"
bench=false

